/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

//#ifndef HZZ4L_ROOHIGHMASS
//#define HZZ4L_ROOHIGHMASS

#include "RooAbsPdf.h"
#include "RooProjectedPdf.h" 
#include "RooProdPdf.h" 
#include "RooSetProxy.h"
#include "RooRealProxy.h"
#include "RooRealVar.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "TH3F.h"
#include "TH1.h"
#include "RooDataHist.h"
#include "RooHistFunc.h"
using namespace RooFit;

class RooHighmass_conv_proj : public RooProjectedPdf {
protected:

  RooRealProxy intpdf;
  RooListProxy _pdfList ;  //  List of funcficients
	RooRealProxy intObs;
	RooSetProxy xlist;
  //RooSetProxy _coefList ;  //  List of funcficients
  //TIterator* _coefIter ;    //! Iterator over funcficient lis
//	TIterator *pdflistItr;
  Double_t evaluate() const ;
	double xgen_min ;
	double xgen_max ;
public:
  RooHighmass_conv_proj() {} ; 
  RooHighmass_conv_proj(const char *name, const char *title,
		       RooProdPdf &_intpdf, RooRealVar &_intObs, const RooArgSet &mreco);
		    
  RooHighmass_conv_proj(const RooHighmass_conv_proj& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooHighmass_conv_proj(*this,newname); }
  inline virtual ~RooHighmass_conv_proj() {}
  
  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

private:

  ClassDef(RooHighmass_conv_proj,1) // Your description goes here...
};
 
//#endif
