/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/


#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "TSpline.h"
#include "RooListProxy.h"
#include "Math/Interpolator.h"

using namespace RooFit;
 
class Width_integral : public RooAbsReal {
public:
  Width_integral() {} ; 
  Width_integral(const char *name, const char *title,
	      RooAbsReal& _a,RooAbsReal& _b,const RooArgList& inCoefList);
  Width_integral(const Width_integral& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Width_integral(*this,newname); }
  inline virtual ~Width_integral() { }

protected:

  RooRealProxy a ;
  RooRealProxy b ;
  RooListProxy _coefList ;  //  List of funcficients
  TIterator* _coefIter ;    //! Iterator over funcficient lis 	
  
  Double_t evaluate() const ;

private:

  ClassDef(Width_integral,1) // Your description goes here...
};
 
